### ISSUE TITLE
naoqisim make 

### ISSUE THREAD

**Issue by wbadry** [omichel/naoqisim#3]
Hello,
I followed your instructions. I am on Windows OS using MSYS2 (32 bit) and Visual C++ 2010 express edition. When I attempt to issue command make I receive the following error:

`bash: cmake: command not found`

Your help is appreciated . Thanks

**Comment by omichel** [comment]
You should use the 64 bit of MSYS2, not the 32 bit version.
I don't believe `cmake` is actually needed to build the naoqisim controller.
I think you only need `make`.
Please follow the installation instructions here: https://github.com/omichel/webots/wiki/Windows-installation including the optional dependencies to setup you development environment.

**Comment by wbadry** [comment]
Thanks @omichel for your response.

I spent a day trying to make it work. I also checked one of the useful threads [https://www.cyberbotics.com/forum?message=8461](url).

Just for a summary:

- MSYS2 64 bit worked on naoqisim but I couldn't make opencv (vision manager).
- These packages must be installed: `unzip` `g++` `opencv`   and `make` . A useful command to use:
`pacman -Ss <your package you need>`
- I tried after that naoqisim.wbt and it was successfully connected to Choreographe (or any NAO API).

Thanks a lot Oliver. I really hope the documentation could be updated as it is quite tricky.

**Comment by omichel** [comment]
Unfortunately, this `naoqisim` software is not supported any more (mostly because it is very buggy and we can't fix it due to design problems in SoftBank proprietary software to which we don't have access). So we won't invest any effort in documenting it any more. But you are welcome to open a new PR to contribute to a better documentation. I will be happy to review it and merge it.

**Comment by omichel** [comment]
I am closing this issue as it seems to be resolved. Feel free to re-open it if it is not the case.
